name: Node.js CI

on:
  push:
    branches: [main]

#jobs to run
jobs:
  #build a server
  build:

    runs-on: ubuntu-latest

    strategy:
      #Can test on different builds
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2 #borrowed from git marketplace
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 #borrowed from git marketplace
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test